In [1]:
print("hello")

hello


# Module 1 Overview of Machine Learning and Tensorflow

## Check Version

In [0]:
import tensorflow as tf

In [3]:
tf.__version__

'1.14.0'

# Module 2 Basic Operations of Tensorflow

### Graph and Session

In [4]:
a = 1.1
b = 2
c = a+b
print(c)

3.1


In [0]:
a = tf.constant(1)
b = tf.constant(2)
c = tf.add(a,b)

In [6]:
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [7]:
sess = tf.Session()
d = sess.run(c)
d

3

In [0]:
# with tf.Session() as sess:
#     print(sess.run(c))

### Tensor Data Types

In [0]:
a = tf.constant(4,dtype=tf.float32)
b = tf.constant(5.6,dtype=tf.float32)
c = tf.multiply(a,b)

In [10]:
sess.run(c)

22.4

In [0]:
# Try out to see what happen
a = tf.constant(4)
b = tf.constant(5.6)
# c = tf.multiply(a,b)

### Ex: Math Operations

In [0]:
a = tf.constant(3,dtype=tf.float32)
b = tf.constant(4.1,dtype=tf.float32)
c = tf.constant(5,dtype=tf.float32)

In [13]:
d = tf.add(tf.multiply(a,b),c)
sess.run(d)

17.3

In [14]:
e = (a*b)+c
sess.run(e)

17.3

### Matrix

In [0]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[4,3],
                 [2,1]])

In [16]:
sess.run(a)

array([[1, 2],
       [3, 4]], dtype=int32)

In [17]:
sess.run(b)

array([[4, 3],
       [2, 1]], dtype=int32)

### Tensor Shape and Slice 

In [18]:
a = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
a
sess.run(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [19]:
tf.shape(a)
sess.run(tf.shape(a))

array([3, 3], dtype=int32)

In [20]:
tf.slice(a,[1,1],[2,2])
sess.run(tf.slice(a,[1,1],[2,2]))

array([[5, 6],
       [8, 9]], dtype=int32)

In [21]:
sess.run(a[1:,1:])

array([[5, 6],
       [8, 9]], dtype=int32)

### Basic Matrix Operations

In [0]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[4,3],
                 [2,1]])

In [23]:
# Transpose
sess.run(tf.transpose(a))

array([[1, 3],
       [2, 4]], dtype=int32)

In [0]:
# Inverse
# sess.run(tf.matrix_inverse(a))

In [25]:
a_float = tf.dtypes.cast(a,tf.float32)
sess.run(tf.matrix_inverse(a_float))

array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)

In [0]:
# Dot Product https://www.tensorflow.org/api_docs/python/tf/tensordot
sess.run(tf.tensordot(a,b, axes=2))

20

In [0]:
# Matrix Multiplication #https://docs.w3cub.com/tensorflow~python/tf/matmul/
sess.run(tf.matmul(a,b))

array([[ 8,  5],
       [20, 13]], dtype=int32)

In [0]:
# Solve A.x = b #https://docs.w3cub.com/tensorflow~python/tf/matrix_solve/
A = tf.constant([[1.,2.],
                 [3.,4.]])
b = tf.constant([[3.],[7.]])
sess.run(tf.matrix_solve(A,b))

array([[1.0000002],
       [0.9999998]], dtype=float32)

In [0]:
### Ex: Matrix Operations

In [0]:
x = tf.constant([[1.1,1.2]],dtype=tf.float32)
w = tf.constant([[1,2],[3,4]],dtype=tf.float32)
b = tf.constant([[2.3,2.5]],dtype=tf.float32)

In [0]:
y = tf.add(tf.matmul(x,w),b)

In [0]:
sess.run(y)

array([[7. , 9.5]], dtype=float32)

### Random Number

In [0]:
# Normal Distribution
a = tf.random_normal([2,3])

In [0]:
sess.run(a)

array([[-0.55812585,  1.5306568 ,  1.1443993 ],
       [ 0.672007  ,  2.950731  , -1.4602225 ]], dtype=float32)

In [0]:
sess.run(a)

array([[-1.5630603 , -1.2940047 ,  0.57919455],
       [-0.94432473,  0.13710642, -0.18516989]], dtype=float32)

In [0]:
# Truncated Normal Distribution #https://www.tensorflow.org/api_docs/python/tf/random/truncated_normal
# values whose magnitude is more than 2 standard deviations from the mean are dropped and re-picked.
a = tf.truncated_normal([2,3])

In [0]:
sess.run(a)

array([[0.83904433, 0.39274144, 0.40448618],
       [0.26976943, 0.5474137 , 0.41440392]], dtype=float32)

In [0]:
# Uniform Distribution #https://www.tensorflow.org/api_docs/python/tf/random/uniform
a = tf.random_uniform([2,3])
sess.run(a)

array([[0.30060565, 0.1690563 , 0.8348317 ],
       [0.09167469, 0.44338906, 0.7855202 ]], dtype=float32)

### Random Seed

In [0]:
tf.set_random_seed(2019)
a = tf.random_uniform([1])

In [0]:
sess = tf.Session()
print(sess.run([a,a]))
print(sess.run([a,a]))
sess.close()

[array([0.11814296], dtype=float32), array([0.11814296], dtype=float32)]
[array([0.371809], dtype=float32), array([0.371809], dtype=float32)]


In [0]:
# a = tf.random_uniform([1])
# # tf.set_random_seed(2019)
# print("Session 1")
# with tf.Session() as sess1:
#     print(sess1.run(a))  # generates 'A1'
#     print(sess1.run(a))  # generates 'A1'

# print("Session 2")
# with tf.Session() as sess2:
#     print(sess2.run(a))  # generates 'A1'
#     print(sess2.run(a))  # generates 'A1'

### Argmax

In [0]:
sess = tf.Session()

In [0]:
a = tf.constant([[1,2],
                 [3,4]])

In [0]:
# Argmin
sess.run(tf.argmin(a))

array([0, 0])

In [0]:
# Argmax
sess.run(tf.argmax(a))

array([1, 1])

### Reduction Operations 

In [0]:
sess.run(tf.reduce_sum(a))

10

In [0]:
sess.run(tf.reduce_sum(a, axis = 0))

array([4, 6], dtype=int32)

In [0]:
sess.run(tf.reduce_sum(a, axis = 1))

array([3, 7], dtype=int32)

In [0]:
sess.run(tf.reduce_mean(a, axis = 0))

array([2, 3], dtype=int32)

In [0]:
sess.run(tf.reduce_mean(a, axis = 1))

array([1, 3], dtype=int32)

### Special Matrices

In [0]:
sess.run(tf.zeros([2,3]))

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [0]:
sess.run(tf.ones([2,3]))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [0]:
sess.run(tf.diag(np.ones(2)))

array([[1., 0.],
       [0., 1.]])

In [0]:
sess.run(tf.fill([2,3],2))

array([[2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [0]:
sess.run(tf.eye(3)) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

### Placeholder

In [0]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = a+b

In [0]:
sess.run(c,feed_dict={a:3,b:7})

10.0

In [0]:
sess.run(c,feed_dict={a:1,b:1})

2.0

### Ex: Placeholder

In [0]:
x = tf.placeholder(tf.float32,shape=[1,2])

In [0]:
x = tf.placeholder(tf.float32,shape=[1,2])
# x = tf.placeholder(tf.float32)
w = tf.constant([[1,2],[3,4]],dtype=tf.float32)
b = tf.constant([[2.3,2.5]],dtype=tf.float32)
y = tf.add(tf.matmul(x,w),b)

In [0]:
sess.run(y,feed_dict={x:[[1.1,1.2]]})

array([[7. , 9.5]], dtype=float32)

### Variable

In [0]:
a = tf.Variable([2.], tf.float32)
b = tf.Variable([1.], tf.float32)
x = tf.placeholder(tf.float32)
y = a * x + b

In [0]:
# sess.run(y,feed_dict={x:1.})

In [0]:
# Method 1
sess.run(a.initializer)

In [0]:
# Method 2
sess.run(tf.variables_initializer(var_list=[b, a]))

In [0]:
# Method 3
init = tf.global_variables_initializer()
sess.run(init)

In [0]:
sess.run(y,feed_dict={x:1.})

array([3.], dtype=float32)

In [0]:
# Assign a new value to the variable with `assign()` or a related method.
sess.run(tf.assign_add(a, [1.0]))

array([3.], dtype=float32)

In [0]:
sess.run(y,feed_dict={x:1.})

array([4.], dtype=float32)