In [0]:
import tensorflow as tf

In [2]:
# Step 0 Data Processing
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("mnist", one_hot=True)

X_train = mnist.train.images
y_train = mnist.train.labels
X_test = mnist.test.images
y_test = mnist.test.labels

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting mnist/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting mnist/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting mnist/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting mnist/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models

In [0]:
# Step 1 Initial setup
X = tf.placeholder(tf.float32,[None,784],name="X")
y = tf.placeholder(tf.float32,[None,10],name="y")

In [4]:
X

<tf.Tensor 'X:0' shape=(?, 784) dtype=float32>

In [5]:
y

<tf.Tensor 'y:0' shape=(?, 10) dtype=float32>

In [0]:
# a = tf.placeholder(tf.float32,[1],name="X")

In [0]:
# a

In [0]:
L1=200
L2=100
L3=50

In [0]:
W1 = tf.Variable(tf.truncated_normal([784,L1],stddev=0.1),name='W1')
B1 = tf.Variable(tf.truncated_normal([L1],stddev=0.1))
W2 = tf.Variable(tf.truncated_normal([L1,L2],stddev=0.1))
B2 = tf.Variable(tf.truncated_normal([L2],stddev=0.1))
W3 = tf.Variable(tf.truncated_normal([L2,L3],stddev=0.1))
B3 = tf.Variable(tf.truncated_normal([L3],stddev=0.1))
W4 = tf.Variable(tf.truncated_normal([L3,10],stddev=0.1))
B4 = tf.Variable(tf.truncated_normal([10],stddev=0.1))

In [10]:
W1

<tf.Variable 'W1:0' shape=(784, 200) dtype=float32_ref>

In [11]:
B1

<tf.Variable 'Variable:0' shape=(200,) dtype=float32_ref>

In [0]:
# Step 2 Model
Y1 = tf.nn.relu(tf.matmul(X,W1)+B1)
Y2 = tf.nn.relu(tf.matmul(Y1,W2)+B2)
Y3 = tf.nn.relu(tf.matmul(Y2,W3)+B3)

In [0]:
# # Ex: Step 2 Model
# Y1 = tf.nn.sigmoid(tf.matmul(X,W1)+B1)
# Y2 = tf.nn.sigmoid(tf.matmul(Y1,W2)+B2)
# Y3 = tf.nn.sigmoid(tf.matmul(Y2,W3)+B3)

In [0]:
Ylogits = tf.matmul(Y3,W4)+B4
yhat = tf.nn.softmax(Ylogits,name="yhat")

In [0]:
# Step 3 Loss Function
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y,logits=Ylogits))

In [0]:
# Step 4 Optimizer
lr = 0.01
train = tf.train.AdamOptimizer(lr).minimize(loss)

In [0]:
# Step 5 Training
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [17]:
training_epochs = 2
batch_size = 100

is_correct = tf.equal(tf.argmax(y,1),tf.argmax(yhat,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

for epoch in range(training_epochs):
    num_batches = int(mnist.train.num_examples/batch_size)
    for i in range(num_batches):
        batch_X, batch_y = mnist.train.next_batch(batch_size)
        train_data = {X: batch_X, y: batch_y}
        sess.run(train, feed_dict=train_data)
        if i%100 == 0:
            print(epoch*num_batches+i+1, "Training accuracy =", sess.run(accuracy, feed_dict=train_data),
              "Loss =", sess.run(loss, feed_dict=train_data))

1 Training accuracy = 0.14 Loss = 2.0360885
11 Training accuracy = 0.77 Loss = 0.6512227
21 Training accuracy = 0.83 Loss = 0.4819017
31 Training accuracy = 0.97 Loss = 0.18570527
41 Training accuracy = 0.89 Loss = 0.45933753
51 Training accuracy = 0.86 Loss = 0.4465626
61 Training accuracy = 0.92 Loss = 0.35842735
71 Training accuracy = 0.93 Loss = 0.26877686
81 Training accuracy = 0.92 Loss = 0.3038362
91 Training accuracy = 0.98 Loss = 0.13782176
101 Training accuracy = 0.92 Loss = 0.34650022
111 Training accuracy = 0.97 Loss = 0.12942976
121 Training accuracy = 0.97 Loss = 0.12372122
131 Training accuracy = 0.96 Loss = 0.15151481
141 Training accuracy = 0.94 Loss = 0.16222751
151 Training accuracy = 0.93 Loss = 0.1798886
161 Training accuracy = 0.97 Loss = 0.11664632
171 Training accuracy = 0.96 Loss = 0.21504883
181 Training accuracy = 0.93 Loss = 0.14133438
191 Training accuracy = 0.95 Loss = 0.167953
201 Training accuracy = 0.94 Loss = 0.29294547
211 Training accuracy = 0.95 Los

In [18]:
test_data = {X:mnist.test.images,y:mnist.test.labels}
print("Testing Accuracy = ", sess.run(accuracy, feed_dict = test_data))

Testing Accuracy =  0.9707


In [0]:
### Save model

In [23]:
saver = tf.train.Saver()
saver.save(sess, "./tf_mnist/tf_mnist")

'./tf_mnist/tf_mnist'

### Restoring Model

In [24]:
saver = tf.train.import_meta_graph('./tf_mnist/tf_mnist.meta')
saver.restore(sess, tf.train.latest_checkpoint('./tf_mnist'))

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./tf_mnist/tf_mnist


In [0]:
# [n.name for n in tf.get_default_graph().as_graph_def().node]

In [26]:
[n.name for n in tf.get_default_graph().as_graph_def().node]

['X',
 'y',
 'truncated_normal/shape',
 'truncated_normal/mean',
 'truncated_normal/stddev',
 'truncated_normal/TruncatedNormal',
 'truncated_normal/mul',
 'truncated_normal',
 'W1',
 'W1/Assign',
 'W1/read',
 'truncated_normal_1/shape',
 'truncated_normal_1/mean',
 'truncated_normal_1/stddev',
 'truncated_normal_1/TruncatedNormal',
 'truncated_normal_1/mul',
 'truncated_normal_1',
 'Variable',
 'Variable/Assign',
 'Variable/read',
 'truncated_normal_2/shape',
 'truncated_normal_2/mean',
 'truncated_normal_2/stddev',
 'truncated_normal_2/TruncatedNormal',
 'truncated_normal_2/mul',
 'truncated_normal_2',
 'Variable_1',
 'Variable_1/Assign',
 'Variable_1/read',
 'truncated_normal_3/shape',
 'truncated_normal_3/mean',
 'truncated_normal_3/stddev',
 'truncated_normal_3/TruncatedNormal',
 'truncated_normal_3/mul',
 'truncated_normal_3',
 'Variable_2',
 'Variable_2/Assign',
 'Variable_2/read',
 'truncated_normal_4/shape',
 'truncated_normal_4/mean',
 'truncated_normal_4/stddev',
 'truncated

In [0]:
graph = tf.get_default_graph()

In [0]:
X = graph.get_tensor_by_name("X:0")
yhat = graph.get_tensor_by_name("yhat:0")

In [29]:
X

<tf.Tensor 'X:0' shape=(?, 784) dtype=float32>

In [0]:
W1 = graph.get_tensor_by_name('Variable:0')

In [31]:
sess.run(W1)

array([-0.17232065, -0.13908024, -0.06844554, -0.10822042, -0.3295538 ,
       -0.09562435, -0.32524592, -0.19042522, -0.14332418, -0.11693115,
        0.08151297, -0.08803406, -0.03321309, -0.05489045,  0.13844003,
        0.20420912,  0.06714901,  0.02653176,  0.01871795,  0.20965144,
        0.14412858, -0.04518751, -0.18107438,  0.24939589, -0.00384891,
        0.29570216, -0.19137166,  0.06508075, -0.19116382, -0.03434891,
       -0.07257037, -0.23216107, -0.2821255 ,  0.01941936,  0.07558957,
       -0.2125149 ,  0.07566084, -0.33772367,  0.10605534,  0.3389024 ,
        0.09466136, -0.00489181,  0.21338135,  0.0908661 , -0.05447074,
       -0.18382359, -0.18041357,  0.05220801, -0.24112438, -0.01248   ,
       -0.15593028,  0.07974061, -0.16318949,  0.00100599, -0.09003835,
       -0.17557287,  0.09527129,  0.00080794,  0.05049376,  0.21914572,
        0.40778276, -0.03046595,  0.06106381, -0.18276371,  0.23977503,
        0.21699348, -0.08538616,  0.00634175, -0.09304394, -0.07

In [34]:
test_predict = sess.run(yhat,feed_dict={X: X_test})
test_predict

array([[6.9144440e-10, 1.2267441e-06, 1.8142964e-07, ..., 9.9998760e-01,
        5.6329032e-08, 8.5266602e-06],
       [4.3004031e-13, 2.5159022e-09, 1.0000000e+00, ..., 1.4514838e-13,
        6.9951683e-10, 3.2261494e-19],
       [7.3674966e-07, 9.9974805e-01, 3.1357133e-05, ..., 5.2801111e-05,
        2.7702543e-05, 2.8750960e-06],
       ...,
       [2.8678695e-11, 4.0542051e-08, 1.0269379e-09, ..., 3.1749183e-05,
        2.2084205e-08, 8.6738919e-06],
       [1.5829659e-07, 1.5478795e-11, 1.9324835e-11, ..., 4.1145798e-09,
        4.2627162e-05, 3.4621017e-09],
       [2.0503541e-10, 4.7038651e-17, 1.3605384e-11, ..., 3.5041571e-19,
        4.1719967e-14, 2.2571382e-16]], dtype=float32)

In [36]:
sess.run(tf.argmax(test_predict, 1))

array([7, 2, 1, ..., 4, 5, 6])

In [40]:
sess.run(tf.argmax(y_test, 1))

array([7, 2, 1, ..., 4, 5, 6])